"use client";
import {useState} from "react";

const nav=[["explorer","◉","Doctor Explorer"],["potential","↗","Doctor Potential"],["ai","✦","AI Support"],["stockist","▣","Stockist Data"]];
const execution=[["plan","▣","My Plan"],["calls","☎","My Calls"],["samples","□","Samples"],["targets","▤","Targets"],["reports","▤","Reports"],["notifications","◉","Notifications"]];

const doctors=[
 {name:"Dr. Ankit Rawal",spec:"Cardiologist",clinic:"HealthCare Clinic",loc:"Veera Desai Rd",score:92,potential:"High",dist:"0.6 km"},
 {name:"Dr. Ramesh Gupta",spec:"Cardiologist",clinic:"City Heart Hospital",loc:"Veera Desai Rd",score:88,potential:"High",dist:"1.2 km"},
 {name:"Dr. Neha Verma",spec:"Cardiologist",clinic:"Lotus Hospital",loc:"Azad Nagar",score:75,potential:"Medium",dist:"1.8 km"},
 {name:"Dr. Amit Shah",spec:"Cardiologist",clinic:"Life Line Hospital",loc:"Veera Desai Rd",score:73,potential:"Medium",dist:"2.1 km"},
 {name:"Dr. Pooja Mehta",spec:"Cardiologist",clinic:"Sunrise Hospital",loc:"Andheri (W)",score:70,potential:"Medium",dist:"2.4 km"},
 {name:"Dr. Suresh Patil",spec:"Diabetologist",clinic:"Care Clinic",loc:"Veera Desai Rd",score:84,potential:"High",dist:"0.9 km"}
];

export default function Home(){
 const [section,setSection]=useState("explorer"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState(doctors[0]);
 const filtered=doctors.filter(d=>Object.values(d).some(v=>String(v).toLowerCase().includes(query.toLowerCase())));
 return <div className="h-screen overflow-hidden flex bg-slate-50">
  <aside className="w-64 bg-slate-900 text-slate-300 flex flex-col justify-between shrink-0">
   <div><div className="p-5 border-b border-slate-800"><h1 className="text-xl font-black text-white flex items-center gap-2"><span className="bg-blue-600 text-white px-2 py-0.5 rounded text-base">MR</span> 3.0</h1><p className="text-xs text-blue-400 font-medium mt-1">Smarter. Faster. Better.</p></div>
   <nav className="p-3 space-y-1 text-sm font-medium">{nav.map(([id,icon,label])=><button key={id} onClick={()=>setSection(id)} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-left ${section===id?"bg-blue-800 text-white border-l-4 border-blue-400":"hover:bg-slate-800"}`}><span className="w-5 text-center">{icon}</span>{label}</button>)}<div className="pt-4 pb-2 px-3 text-[11px] uppercase tracking-wider text-slate-500 font-bold">Execution</div>{execution.map(([id,icon,label])=><button key={id} onClick={()=>setSection(id)} className={`w-full flex items-center gap-3 px-3 py-2 rounded-lg text-left hover:bg-slate-800 ${section===id?"text-white":""}`}><span className="w-5 text-center">{icon}</span>{label}</button>)}</nav></div>
   <div className="p-4 border-t border-slate-800 text-xs text-slate-500">MR 3.0 · Production foundation</div>
  </aside>
  <main className="flex-1 flex flex-col min-w-0">
   <header className="bg-white border-b border-slate-200 px-6 py-3 flex items-center justify-between shrink-0"><div className="flex items-center gap-4 flex-1 max-w-2xl"><button className="text-slate-500 text-lg">☰</button><div className="relative flex-1"><span className="absolute left-3.5 top-2.5 text-slate-400">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search doctor by name, specialty, brand, molecule..." className="w-full pl-10 pr-4 py-2 bg-slate-100 border border-transparent rounded-full text-sm outline-none focus:bg-white focus:border-blue-500"/></div></div><div className="flex items-center gap-5"><button onClick={()=>setSection("ai")} className="relative">♧<span className="absolute -top-1 -right-2 bg-blue-600 text-white text-[9px] w-4 h-4 rounded-full">2</span></button><span className="text-sm font-bold">Amit Rawat</span><span className="text-xs text-slate-500">Territory Manager</span></div></header>
   <div className="flex-1 overflow-y-auto p-6">
    {section==="explorer"&&<section className="space-y-6"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h2 className="text-2xl font-black">Doctor Explorer</h2><p className="text-sm text-slate-500">Find doctors by location, patch & specialty</p></div><div className="flex gap-2 bg-white p-2 rounded-xl border border-slate-200 shadow-sm"><select className="text-xs font-semibold bg-white border border-slate-200 px-3 py-2 rounded-lg"><option>Veera Desai</option><option>Vile Parle</option><option>Versova</option></select><select className="text-xs font-semibold bg-white border border-slate-200 px-3 py-2 rounded-lg"><option>All Specialties</option><option>Cardiologist</option><option>Diabetologist</option></select></div></div><div className="grid grid-cols-1 xl:grid-cols-12 gap-6"><div className="xl:col-span-7 bg-white rounded-2xl border border-slate-200 p-5 shadow-sm"><div className="flex justify-between mb-4"><h3 className="font-bold">Doctors in Veera Desai</h3><span className="text-xs text-slate-500">{filtered.length} results</span></div><div className="space-y-2">{filtered.map(d=><button key={d.name} onClick={()=>{setSelected(d);setSection("potential")}} className="w-full text-left border border-slate-100 hover:border-blue-300 hover:bg-blue-50/40 rounded-xl p-4 flex items-center justify-between"><div><div className="font-bold text-slate-900">{d.name}</div><div className="text-xs text-slate-500 mt-1">{d.spec} · {d.clinic} · {d.loc}</div></div><div className="text-right"><div className="font-black text-blue-700">{d.score}</div><div className={`text-[10px] font-bold ${d.potential==="High"?"text-emerald-600":"text-amber-600"}`}>{d.potential} Potential</div></div></button>)}</div></div><div className="xl:col-span-5 bg-white rounded-2xl border border-slate-200 p-5 shadow-sm min-h-[420px]"><div className="font-bold mb-3">Territory Map</div><div className="h-[350px] rounded-xl bg-slate-100 border border-slate-200 relative overflow-hidden"><div className="absolute inset-8 border-2 border-dashed border-slate-300 rounded-[30%]"></div>{doctors.map((d,i)=><button key={d.name} onClick={()=>setSelected(d)} style={{left:`${15+(i*13)%70}%`,top:`${18+(i*19)%65}%`}} className={`absolute w-8 h-8 rounded-full text-xs font-black shadow ${selected.name===d.name?"bg-blue-600 text-white":"bg-white text-blue-700 border border-blue-300"}`}>{i+1}</button>)}</div></div></div></section>}
    {section==="potential"&&<section className="space-y-6"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-black">Doctor Potential & Deep Profile</h2><p className="text-sm text-slate-500">Detailed performance & prescribing insights</p></div><div className="flex gap-2"><button className="bg-blue-50 text-blue-700 font-semibold px-4 py-2 rounded-xl text-xs">＋ Add to Plan</button><button className="bg-blue-600 text-white font-semibold px-4 py-2 rounded-xl text-xs">☎ Log Call</button></div></div><div className="bg-gradient-to-r from-blue-900 via-blue-800 to-indigo-900 text-white p-6 rounded-2xl shadow-md"><h3 className="text-xl font-black">{selected.name}<span className="ml-3 bg-emerald-500/20 text-emerald-300 text-[10px] px-2 py-1 rounded-full">{selected.potential} Potential</span></h3><p className="text-blue-200 text-sm mt-1">{selected.spec} · {selected.clinic}</p><p className="text-xs text-slate-300 mt-2">⌖ {selected.loc} · {selected.dist}</p></div><div className="grid xl:grid-cols-3 gap-5"><div className="xl:col-span-2 bg-white rounded-2xl border border-slate-200 p-5"><h3 className="font-bold mb-4">Prescribing & Opportunity</h3><div className="grid grid-cols-3 gap-3">{[["Potential Score",selected.score],["Monthly Scripts","185"],["Conversion","18.2%"]].map(x=><div key={x[0]} className="bg-slate-50 rounded-xl p-4"><div className="text-xs text-slate-400 uppercase">{x[0]}</div><div className="text-2xl font-black mt-1">{x[1]}</div></div>)}</div><div className="mt-5 bg-blue-50 border border-blue-100 rounded-xl p-4 text-sm text-blue-900"><b>Next Best Action</b><p className="mt-1">Pitch the most relevant product based on this doctor&apos;s profile and previous discussion.</p></div></div><div className="bg-white rounded-2xl border border-slate-200 p-5"><h3 className="font-bold">Doctor Availability</h3><div className="mt-4 bg-blue-50 border border-blue-100 p-3 rounded-xl"><div className="text-xs uppercase text-blue-700 font-bold">Best Time to Visit</div><div className="font-black text-blue-900 mt-1">10:30 AM – 12:30 PM</div><div className="text-xs text-blue-700">Mon–Sat</div></div><div className="mt-5 text-xs text-slate-500">Primary Chemist</div><div className="mt-2 bg-slate-50 p-3 rounded-xl border border-slate-100"><b>Noble Pharmacy</b><div className="text-xs text-slate-500">Veera Desai Rd · 185 scripts/mo</div><span className="text-xs text-emerald-700 font-bold">In Stock</span></div></div></div></section>}
    {section==="ai"&&<section className="space-y-6"><div><h2 className="text-2xl font-black">AI Support</h2><p className="text-sm text-slate-500">Your AI assistant for any query</p></div><div className="grid xl:grid-cols-12 gap-6"><div className="xl:col-span-8 bg-white rounded-2xl border border-slate-200 flex flex-col h-[600px] shadow-sm"><div className="flex-1 p-5"><div className="flex gap-3"><div className="w-9 h-9 rounded-full bg-blue-600 text-white flex items-center justify-center font-bold text-xs">AI</div><div className="bg-slate-100 rounded-2xl p-4 max-w-xl text-sm"><b>Hi Amit! 👋</b><p className="mt-1">I&apos;m MR 3.0 AI Assistant. I can help you find the best products, understand doctor preferences and more.</p></div></div></div><div className="p-4 border-t border-slate-200 flex gap-3"><input placeholder="Ask me anything..." className="flex-1 bg-slate-100 rounded-full px-5 py-3 text-sm outline-none"/><button className="bg-blue-600 text-white w-11 h-11 rounded-full">➤</button></div></div><div className="xl:col-span-4 bg-gradient-to-br from-indigo-900 via-blue-900 to-slate-900 text-white rounded-2xl p-5 h-fit"><h3 className="font-bold">✦ AI Recommendation</h3><div className="mt-4 text-sm space-y-2"><div className="bg-white/10 rounded-xl p-3">CardiaPain Plus <span className="float-right">98%</span></div><div className="bg-white/10 rounded-xl p-3">CardiaRelief <span className="float-right">Alternative</span></div></div></div></div></section>}
    {section==="stockist"&&<section className="space-y-6"><div><h2 className="text-2xl font-black">Stockist Data</h2><p className="text-sm text-slate-500">Real-time stockist performance & availability</p></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[["Total Stockists","48"],["In Stock","41"],["Low Stock","5"],["Out of Stock","2"]].map(x=><div key={x[0]} className="bg-white p-4 rounded-2xl border border-slate-200 shadow-sm"><div className="text-xs uppercase tracking-wider font-semibold text-slate-400">{x[0]}</div><div className="text-2xl font-black mt-1">{x[1]}</div></div>)}</div></section>}
    {!["explorer","potential","ai","stockist"].includes(section)&&<section><h2 className="text-2xl font-black">{execution.find(x=>x[0]===section)?.[2]}</h2><p className="text-sm text-slate-500 mt-1">This module is being connected to the production database.</p><div className="mt-6 bg-white border border-slate-200 rounded-2xl p-8">The navigation and module boundary are established. Persistent workflows will replace the prototype placeholders in the next implementation pass.</div></section>}
    <footer className="mt-8 bg-white border border-slate-200 rounded-2xl p-4 flex flex-wrap items-center justify-between gap-4 shadow-sm"><div className="flex flex-wrap gap-6 text-xs font-semibold text-slate-600"><span>Total Doctors: <b className="text-slate-900">1,243</b></span><span>High Potential: <b className="text-emerald-600">312 (25.1%)</b></span><span>Total Calls: <b>156</b></span><span>Samples: <b>320</b></span><span>Conversion Rate: <b className="text-blue-600">18.2%</b></span></div><button onClick={()=>setSection("plan")} className="bg-blue-600 text-white font-semibold text-xs px-4 py-2.5 rounded-xl">Go to My Plan →</button></footer>
   </div>
  </main>
 </div>
}